name: Wiz Scan
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  wiz-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      POLICY: "Block-VM" # Set the desired Wiz CLI policy to use
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@de0fac2ef9f7dc9bfc8b0f8afc9b2b6d99d6f36b # v6.0.2

      - name: Build the Docker image
        run: docker build . --tag contrast-mcp:dev

      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Run Wiz CLI container image scan
        run: ./wizcli scan container-image contrast-mcp:dev --client-id "$WIZ_CLIENT_ID" --client-secret "$WIZ_CLIENT_SECRET" --assist-migration --policies "$POLICY" --csv-output-file="mcp-contrast-wiz-report.zip" --by-policy-hits="BLOCK" --show-ignored-by-grace-period
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Capture Wiz Output
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mcp-contrast-wiz-report
          path: |
            mcp-contrast-wiz-report.zip
